# Generated by Django 3.2.5 on 2021-08-12 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True
    ID_PK = models.BigAutoField(
        auto_created=True,
        primary_key=True,
        serialize=False,
        verbose_name='ID'
    )
    AUTHOR_FK = models.ForeignKey(
        on_delete=django.db.models.deletion.CASCADE,
        to='api.author'
    )
    BOOK_FK = models.ForeignKey(
        on_delete=django.db.models.deletion.CASCADE,
        to='api.book'
    )

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', ID_PK),
                ('name', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', ID_PK),
                ('title', models.CharField(max_length=45)),
                ('edition', models.CharField(max_length=15)),
                ('publication_year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BookAuthor',
            fields=[
                ('id', ID_PK),
                ('author', AUTHOR_FK),
                ('book', BOOK_FK),
            ],
        ),
    ]
