# Generated by Django 3.2.5 on 2021-08-14 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', 'create_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['publication_year', 'title']},
        ),
    ]
