# Generated by Django 3.2.5 on 2021-08-21 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_auto_20210814_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(to='api.Author'),
        ),
    ]
