name: Docker Image Build CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      USERNAME: ${{ secrets.USERNAME }}
      EMAIL: ${{ secrets.EMAIL }}
      PASSWORD: ${{ secrets.PASSWORD }}
    steps:
    - uses: actions/checkout@v3
    - name: Make envfile
      run:  |
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> ${{ github.workspace }}/libapi/libapi/.env
          echo "USERNAME=${{ secrets.USERNAME }}" >> ${{ github.workspace }}/libapi/libapi/.env
          echo "EMAIL=${{ secrets.EMAIL }}" >> ${{ github.workspace }}/libapi/libapi/.env
          echo "PASSWORD=${{ secrets.PASSWORD }}" >> ${{ github.workspace }}/libapi/libapi/.env
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
