name: Docker Image Build CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      USERNAME: ${{ secrets.USERNAME }}
      EMAIL: ${{ secrets.EMAIL }}
      PASSWORD: ${{ secrets.PASSWORD }}
    steps:
    - uses: actions/checkout@v3
    - name: Make envfile
      uses: SpicyPizza/create-envfile@v2.0
      with:
        envkey_SECRET_KEY: ${{ secrets.SECRET_KEY }}
        envkey_USERNAME: ${{ vars.USERNAME }}
        envkey_EMAIL: ${{ vars.EMAIL }}
        envkey_PASSWORD: ${{ vars.PASSWORD }}
        directory: ${{ github.workspace }}/libapi/libapi
        file_name: .env
        fail_on_empty: false
        sort_keys: false
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
